version: '2.4'

services:
  node:
    build:
      context: .
      target: dev
    ports:
      - 3000:8080
    volumes:
      - .:/node/app
      - /node/app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./compose.conf:/etc/nginx/conf.d/default.conf
